#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRsensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,          servo1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightwheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     arm2,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Controls.h"

/*
task main(){
	//Move Forward
	//	waitForStart();
		wait1Msec(2000);
    time1[T1] = 0;
		armraise();
		wait1Msec(1000);



		motor[rightwheel] = 0;
		motor[leftwheel] = 17;
		wait1Msec(1500);

		motor[rightwheel] = 15;
		motor[leftwheel] = 15;
		wait1Msec(2000);

		motor[leftwheel] = -32;
		motor[rightwheel] = 32;
		wait1Msec(1100);

		motor[rightwheel] = -13;
		motor[leftwheel] = -13;

		wait1Msec(1500);
		motor[rightwheel] = 0;
		motor[leftwheel] = 0;

		wait1Msec(1500);

		while (time1[T1]<30000) {
			int ir = SensorValue[IRsensor];
			nxtDisplayTextLine(0,"%d",ir);
			nxtDisplayTextLine(3,"%d",time1[T1]);
			if (time1[T1]> 25000)
						{
							motor[leftwheel] = 0;
							motor[rightwheel] = 0;
							claw(1);
						}
			switch(ir)
			{
				case 0:
					nxtDisplayTextLine(4,"Searching...");
						motor[rightwheel] = 25;
						motor[leftwheel] = 0;
					break;
				case 1:
					nxtDisplayTextLine(4,"turning Left...");
						motor[rightwheel] = 23;
						motor[leftwheel] = 0;
					break;
				case 2:
					nxtDisplayTextLine(4,"turning Left...");
						motor[rightwheel] = 20;
						motor[leftwheel] = 0;
					break;
				case 3:
					nxtDisplayTextLine(4,"turning Left...");
						motor[rightwheel] = 18;
						motor[leftwheel] = 0;
					break;
				case 4:
					nxtDisplayTextLine(4,"turning Left...");
						motor[rightwheel] = 15;
						motor[leftwheel] = 0;
					break;
				case 5:
					nxtDisplayTextLine(4, "move forwards...");
						motor[leftwheel] = 20;
						motor[rightwheel] = 20;
					break;
				case 6:
					nxtDisplayTextLine(4, "turning Right...");
						motor[rightwheel] = 0;
						motor[leftwheel] = 15;
					break;
				case 7:
					nxtDisplayTextLine(4, "turning Right...");
						motor[rightwheel] = 0;
						motor[leftwheel] = 18;
					break;
				case 8:
					nxtDisplayTextLine(4, "turning Right...");
						motor[rightwheel] = 0;
						motor[leftwheel] = 20;
					break;
				case 9:
					nxtDisplayTextLine(4, "turning Right...");
						motor[rightwheel] = 0;
						motor[leftwheel] = 23;
					break;
		  }
		}
	nxtDisplayTextLine(1,"DONE");
	motor[leftwheel] = 0;
	motor[rightwheel] = 0;

	wait1Msec(1000);

}

void armraise () {
	motor[arm] = 100;
	wait1Msec(1000);
	motor[arm] = 0;
	nxtDisplayTextLine(5,"raising the arm...");
}
void claw (int num) {
	motor[motorA] = 100*num;
	wait1Msec(1000);
	motor[motorA] = 0;
}
*/
//~~~~~~~~~~~~~~~~~~~~~~~~~~
task main() {
	waitForStart();
	armraise(1,60,700);
	 time1[T1] = 0;

while (time1[T1]<25000)
{
		int	ir = SensorValue[IRsensor];
		print(0,"%d",ir);
		motor[leftwheel] = 40;
			motor[rightwheel] = 40;
			wait1Msec(500);
			motor[leftwheel] = 0;
			motor[rightwheel] = 0;
 		if (ir != 5)
 		{
			motor[leftwheel] = 30;
			motor[rightwheel] = 30;
		}
	  else
		{
		wait1Msec(480);
		motor[leftwheel] = -20;
		motor[rightwheel] = 20;
		wait1Msec(1450);
		motor[leftwheel] = 20;
		motor[rightwheel] = 20;
		wait1Msec(700);
		motor[leftwheel] = 0;
		motor[rightwheel] = 0;
		claw(1);
		wait1Msec(200);
		motor[leftwheel] = -20;
		motor[rightwheel] = -20;
		wait1Msec(1300);
		motor[leftwheel] = 20;
		motor[rightwheel] =-20;
		wait1Msec(1400);
		motor[leftwheel] = 0;
		motor[rightwheel] =0;
		break;
	  }
	  //RUN ON RAMP

}
}
