#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  motorA,          sensor1,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightwheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     arm2,          tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Controls.h"

task main()
{
	beep();
  //waitForStart();
	print(5,"Starting...");
	while (true)
	{
		getJoystickSettings(joystick);
		motor[leftwheel] = joystick.Left;
		motor[rightwheel] = joystick.Right;

		buttonPress (LeftTrigger)
		{
			print(5, "Claw opening...");
			claw(1);
		}
		buttonPress (RightTrigger)
		{
			print(5, "Claw closing...");
			claw(-1);
		}
		buttonPress (RightButton)
		{
			print(5,"Arm raising...");
			motor[arm] = power;
			motor[arm2] = power;
		}
		buttonPress (LeftButton)
		{
			print(5,"Arm descending...");
			motor[arm] = -power;
			motor[arm2] = -power;
		}
		else
		{
			motor[arm] = noPower;
			motor[arm2] = noPower;
			print(5,"");
			ClearSounds();
		}

	}

}
