#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  motorA,          sensor1,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightwheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     arm2,          tmotorTetrix, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define Left joy1_y1
#define Right joy1_y2

#include "JoystickDriver.c"

void claw(int num);
void beep();

task main()
{
	beep();
 // waitForStart();
	nxtDisplayTextLine(5,"starting...");
	while (true)
	{
		getJoystickSettings(joystick);
		motor[leftwheel] = joystick.Left;
		motor[rightwheel] = joystick.Right;

		if ( joy1Btn(7) ==  1)
		{

			claw(1);

		}
		if ( joy1Btn(8) ==  1 )
		{

			claw(-1);

		}
		if ( joy1Btn(6) ==  1)
		{

			motor[arm] = power;
			motor[arm2] = power;

		}
		if ( joy1Btn(5) ==  1)
		{

			motor[arm] = power;
			motor[arm2] = power;

		}
		else
		{
			motor[arm] = 0;
			motor[arm2] = 0;
			nxtDisplayTextLine(5,"");
			ClearSounds();
		}

	}

}

void claw(int num)
{
	beep();
	motor[motorA] = 100*num;
	wait1Msec(100);
	motor[motorA] = 0;


}

void beep()

{
	PlayTone(42,42);
}
